language: go
go:
- 1.10.x
git:
  depth: 1
notifications:
  email: false
script:
- go test -v ./...
- mkdir bin
- GO111MODULE=on GOOS=linux go build -o bin/assume-role-arn-linux cmd/assume-role-arn/main.go
- GO111MODULE=on GOOS=darwin go build -o bin/assume-role-arn-osx cmd/assume-role-arn/main.go
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $OAUTH_KEY
  file:
    - bin/assume-role-arn-linux
    - bin/assume-role-arn-osx
  on:
    repo: nordcloud/assume-role-arn
    tags: true
